name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  BUILD_AND_PUSH_DOCKER_IMAGE:
    name: Build and Push SQL Server Docker Image

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Context
        uses: actions/checkout@v3
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_MANAGEMENT }}
          password: ${{ secrets.DOCKERHUB_TOKEN_MANAGEMENT }}

      - name: Build app Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME_MANAGEMENT }}/${{ secrets.DOCKERHUB_IMAGE_NAME_MANAGEMENT }}

      - name: Push app Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME_MANAGEMENT }}/${{ secrets.DOCKERHUB_IMAGE_NAME_MANAGEMENT }}
        